Шапошникова Наталья
urfu-2016/markup-task-7 pull request #36
Opened 2016-11-21 20:38 UTC by Dobrbobr

2016-11-21 20:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-22 19:53 UTC, Dodo888 commented on index.html
> +        <div class="rating-info second">
❗️ А можно как-нибудь обойтись без подсчета порядке при изменении рейтинга или добавлении нового вида?

2016-11-22 19:54 UTC, Dodo888 commented
❗️ Разные отступы у столбцов
![image](https://cloud.githubusercontent.com/assets/10964067/20539582/58efd162-b117-11e6-9039-03fa6cd024fb.png)

2016-11-22 19:55 UTC, Dodo888 commented
❗️ `Левая колонка с меню всегда подстраивается под высоту контейнера с фотками, а правая (рейтинг) - по контенту внтури нее.`
![image](https://cloud.githubusercontent.com/assets/10964067/20539606/6fba20be-b117-11e6-8241-ee984a31b75a.png)

2016-11-22 19:56 UTC, Dodo888 commented
❗️ Плашка не должна появляться при наведении на неактивных котиков
![image](https://cloud.githubusercontent.com/assets/10964067/20539650/9857d980-b117-11e6-9a3f-09c8449ddfb7.png)

2016-11-22 19:56 UTC, Dodo888 commented
❗️ Плашка вылезает за пределы изображения
![image](https://cloud.githubusercontent.com/assets/10964067/20539678/b0b077da-b117-11e6-8cdb-fb8dbb3def88.png)

2016-11-22 19:58 UTC, Dodo888 commented
Не получилось задать рейтинг 9 (поменял значение на 9 и класс на value-9)
![image](https://cloud.githubusercontent.com/assets/10964067/20539737/f81834c8-b117-11e6-98dc-c8003d260eb5.png)

2016-11-22 20:00 UTC, Dodo888 commented
❗️ Футер не прикрепился к низу
![image](https://cloud.githubusercontent.com/assets/10964067/20539818/4982735a-b118-11e6-8d35-3b346b200e70.png)

2016-11-22 20:03 UTC, Dodo888 commented
❗️ При маленькой ширине экрана ломается макет расположения изображений
![image](https://cloud.githubusercontent.com/assets/10964067/20539890/9da33564-b118-11e6-8be0-7495055b55ec.png)

2016-11-22 20:05 UTC, Dodo888 commented
Во всех браузерах страница выглядит одинаково, хорошо располагаются изображения. Оставил небольшие замечания)

2016-11-22 20:05 UTC, Dodo888 commented
🍅

2016-11-23 20:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-23 20:16 UTC, Dobrbobr commented
🍏

2016-11-25 19:36 UTC, Dodo888 commented
❗️ Все равно разные отступы
![image](https://cloud.githubusercontent.com/assets/10964067/20634227/55002c54-b370-11e6-88d7-f03f1b1e0bf8.png)

2016-11-25 19:38 UTC, Dodo888 commented
❗️ Футер не прикрепился к низу
![image](https://cloud.githubusercontent.com/assets/10964067/20634265/b59c694c-b370-11e6-9d32-41bfcf927720.png)

2016-11-25 19:40 UTC, Dodo888 commented
❗️ 10 не влезает в строку
![image](https://cloud.githubusercontent.com/assets/10964067/20634282/ddce4818-b370-11e6-90c1-5b4f2c5b11cd.png)

2016-11-25 19:44 UTC, Dodo888 commented
В остальном хорошо)

2016-11-25 19:44 UTC, Dodo888 commented
🚀

2016-11-26 09:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-26 09:02 UTC, Dobrbobr commented
🍏

2016-11-28 11:29 UTC, mokhov commented
На маленьких экранах уезжает левая колонка
![2016-11-28 16-28-09](https://cloud.githubusercontent.com/assets/357689/20666776/1a6b0042-b590-11e6-81c0-76f25eb7a265.png)

2016-11-28 11:29 UTC, mokhov commented
На больших котики пикселизуются и видно что отступы не те
![2016-11-28 16-28-55](https://cloud.githubusercontent.com/assets/357689/20666808/415ad18c-b590-11e6-9e35-eb877b1b6358.png)

2016-11-28 11:30 UTC, mokhov commented
Если выбрать категорию «Другая» то черный котик не реагирует но ховер, хотя выглядит активным

2016-11-28 11:31 UTC, mokhov commented
Цифры прижались к шкале
![2016-11-28 16-30-57](https://cloud.githubusercontent.com/assets/357689/20666853/794835bc-b590-11e6-9797-6656745b2bd4.png)

2016-11-28 11:36 UTC, mokhov requested changes
🍅

2016-11-28 11:36 UTC, mokhov commented on index.css
> +    font-family: Cambria;
Не хватает семейства шрифтов по-умолчанию

2016-11-28 11:36 UTC, mokhov commented on index.css
> +.value-1 .value:before
👍

2016-11-28 11:36 UTC, mokhov commented on index.css
> +.value-10 .value:before,
Тут почти хорошо, только давай уже использовать БЭМ. Т.е тут надо назвать класс не `value` в вакууме, а, например, `rating-value`, тем самым подчеркнув связь с блоком rating, ну и почитай немного о методологии, она не сложная: https://ru.bem.info/methodology/

2016-11-28 11:36 UTC, mokhov commented on index.html
> +                <p>Бенгальская</p>
Не дотягивает до параграфа

2016-11-28 11:36 UTC, mokhov commented on index.html
> +    <p class="address">Наш адрес: улица Котовая, д.5</p>
Есть более семантичный тег

2016-11-28 11:36 UTC, mokhov commented on index.html
> +    <nav class="button-choice">
👍 молодец чо вынесла

2016-11-28 17:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-28 17:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-11-28 17:33 UTC, Dobrbobr commented
🍏

2016-11-28 18:33 UTC, mokhov commented
В идеале ещё хочется что вся страница была отцентрована и вертикальные отступы. ну да ладно, за старательность молодец

2016-11-28 18:33 UTC, closed without merging