Загнойко Александр
urfu-2016/markup-task-7 pull request #44
Opened 2016-12-07 20:32 UTC by FoKycHuK

коты мне будут сниться

2016-12-07 20:32 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-07 22:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-07 22:28 UTC, mokhov requested changes
🍅

2016-12-07 22:28 UTC, mokhov commented on index.css
> +input:checked ~ .third
А если я добавлю рейтинг с цифрой 5, то какой у него будет класс?

2016-12-07 22:28 UTC, mokhov commented on index.html
> +            <div class="cell breed1 default-size">
Картинка + подпись – есть более семантичные теги

2016-12-07 22:28 UTC, mokhov commented on index.html
> +            По убыванию <input type="checkbox">
Хочу иметь возможность кликать по тексту

2016-12-07 22:28 UTC, mokhov commented on index.html
> +                <div class="top-element"><div class="scale ten"></div>10</div>
Зачем нужен отдельный класс scale, когда можно просто заматчиться на элемент внутри `top-element`?

2016-12-07 22:28 UTC, mokhov commented on index.html
> +        <address>Наш адрес: ул. Котовая, д.5</address>
https://github.com/urfu-2016/markup-task-7/pull/42#discussion_r91282467

2016-12-07 22:31 UTC, FoKycHuK commented on index.css
> +input:checked ~ .third
first-point-five?)

2016-12-07 22:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-07 22:55 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-07 22:56 UTC, FoKycHuK commented
🍏

2016-12-07 23:22 UTC, mokhov commented
Ну радикально ничего не поменялось – я должен теперь знать что мне в элемент с классом thrid нужно положить число, которое где-то между n и n-m. Думай дальше и не торопись

2016-12-07 23:23 UTC, mokhov commented
🍅

2016-12-08 04:18 UTC, FoKycHuK commented
я, к сожалению, уезжаю до вс, но в дороге обязательно подумаю об этом :)

2016-12-12 19:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2016-12-12 19:07 UTC, FoKycHuK commented
🍏

2016-12-13 18:12 UTC, closed without merging